{% set name = "requirements-parser" %}
{% set version = "0.3.1" %}
{% set sha256 = "3852277618e653dd1d8fa4129e59b4338358dffafeb3d5106e9f88504db9c460" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - setuptools

test:
  imports:
    - requirements

about:
  home: https://github.com/davidfischer/requirements-parser
  license: BSD
  license_file: LICENSE.rst
  summary: This is a small Python module for parsing Pip requirement files.

  description: |
    This is a small Python module for parsing Pip requirement files.
    The goal is to parse everything in the Pip requirement file format spec.
  doc_url: https://requirements-parser.readthedocs.io/
  dev_url: https://github.com/davidfischer/requirements-parser

extra:
  recipe-maintainers:
    - CurtLH
